<a href="https://colab.research.google.com/github/sammothxc/math215-w24/blob/main/labs/Least_squares_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Lab 6 - Least squares I**

Enter your code in the spaces provided. Do not change any of the variable names or function names that are already provided for you. In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.

In [103]:
# Do not edit this cell.

LabID="Lab6"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

**Enter your name, section number, and BYU NetID**

In [104]:
# Enter your first and last names in between the quotation marks.

first_name="Sam"

last_name="Warr"

# Enter your Math 215 section number in between the quotation marks.

section_number="01"

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER!

BYUNetID="warrior8"

**Import NumPy**

In [105]:
import numpy as np

**Problem 1**

In [106]:
# Replace the values of 0 with the NumPy arrays from Problem 1.

X1=np.array([[1,5],[1,10],[1,15],[1,20],[1,25],[1,30],[1,35],[1,40],[1,45],[1,50]])

Y1=np.array([3.33,4.43,4.39,5.23,5.67,6.06,7.01,7.16,8.03,8.78])

**Problem 2**

In [107]:
# Replace the values of 0 with the normal equation coefficient matrix and normal equation right-hand side respectively from Problem 2.

normal_coef1=np.matmul(np.transpose(X1),X1)

normal_vect1=np.matmul(np.transpose(X1),Y1)

**Problem 3**

In [108]:
# Replace the value of 0 with the least squares solution beta1 you found in Problem 3.

beta1=np.linalg.solve(normal_coef1,normal_vect1)

In [109]:
# Define a function whose graph is the line of best fit.

def ls1_line(x):
  return beta1[0]+beta1[1]*x


In [110]:
import matplotlib.pyplot as plt

# Construct your plot of ls1_line and the corresponding data points here. Put all of your code to create the plots inside the function below.

def create_plots1():
  # Put all of your code to create the plots here.
  return None

In [111]:
# Replace the value of 0 with your prediction of the satellite's velocity at t=60.

pred1=ls1_line(60)

**Problem 4**

In [112]:
# Replace the values of 0 with the NumPy arrays from Problem 4.

X2=np.array([[5,25],[10,100],[15,225],[20,400],[25,625],[30,900],[35,1225],[40,1600],[45,2025],[50,2500]])

Y2=np.array([20.57,87.48,197.45,347.67,546.12,784.35,1066.02,1390.97,1761.85,2177.34])

**Problem 5**

In [113]:
# Replace the values of 0 with the normal equation coefficient matrix and normal equation right-hand side, and least squares solution from Problem 5.

normal_coef2=np.matmul(np.transpose(X2),X2)

normal_vect2=np.matmul(np.transpose(X2),Y2)

beta2=np.linalg.solve(normal_coef2,normal_vect2)
print(beta2)

[0.03934604 0.8695467 ]


**Problem 6**

In [114]:
# Define a function whose graph is the parabola of best fit.

def ls2_par(x):
  return beta2[0]*x+beta2[1]*x**2

In [115]:
# Construct your plot of ls2_par and the corresponding data points here. Put all of your code to create the plots inside the function below.

def create_plots2():
  # Put all of your code to create the plots here.
  return None

In [116]:
# Replace the value of 0 with your prediction of the satellite's position at t=60.

pred2=ls2_par(60)

**Problem 7**

In [122]:
# Replace the values of 0 with the NumPy arrays from Problem 7.

Y3=np.array([np.log(0.389),np.log(0.724),np.log(1),np.log(1.524),np.log(5.2),np.log(9.510)])

X3=np.array([[1,np.log(87.77)],[1,np.log(224.7)],[1,np.log(365.25)],[1,np.log(686.95)],[1,np.log(4332.62)],[1,np.log(10759.2)]])
print(X3)
print(Y3)

[[1.         4.47471976]
 [1.         5.41476618]
 [1.         5.90058205]
 [1.         6.53226151]
 [1.         8.3739231 ]
 [1.         9.28351648]]
[-0.94417594 -0.32296389  0.          0.42133846  1.64865863  2.25234388]


In [118]:
# Replace the values of 0 with the normal equation coefficient matrix and normal equation right-hand side from Problem 7.

normal_coef3=np.matmul(np.transpose(X3),X3)

normal_vect3=np.matmul(np.transpose(X3),Y3)
print(normal_coef3)
print(normal_vect3)

[[  6.          39.97976908]
 [ 39.97976908 283.13638503]]
[ 3.05520114 31.4940084 ]


In [121]:
# Replace the value of 0 with the least squares solution from Problem 7.

beta3=np.linalg.solve(normal_coef3,normal_vect3)
print(beta3)

[-3.92372365  0.66527505]


**Problem 8**

In [123]:
# Replace the values of 0 with your predictions for the semi-major axes of Uranus and Neptune.
def ls3_line(x):
  return (x ** beta3[1]) * (np.exp(beta3[0]))


pred_Uran=ls3_line(30687.15)

pred_Nept=ls3_line(60190.03)

print(pred_Uran)
print(pred_Nept)

19.098916723205367
29.898329881455


**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.   

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to [gradescope.com](https://gradescope.com) for grading.